spring:
  application:
    name: oaes-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/oaes_db
    username: postgres
    password: "1234"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: ThisIsASecretKeyForOAESJwtAuthenticationSystem2026SuperSecureSecretKey123456789
  expiration: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    com.oaes: DEBUG

storage:
  workspace-root: D:/OAES/Workspaces

gemini:
  api-key: AIzaSyBKoTHjmB9CFAj5oUT0HSRvtLcaVev1R64
  model: gemini-flash-latest

ollama:
  url: http://localhost:11434/api/chat
  model: qwen3:8b